version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - 3002:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./sandbox:/var/sandbox
    restart: always

  react:
    build:
      dockerfile: react/Dockerfile
      target: ${ENV:-development}
    ports:
      - "3003:80"
    volumes:
      - .:/var/www/html
    env_file:
      - src/.env
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-X",
          "POST",
          "-H",
          "Content-Type: application/json",
          "-d",
          '{"query":"{ __typename }"}',
          "http://localhost:80/graphql",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  php:
    build:
      dockerfile: php/Dockerfile
      target: ${ENV:-development}
    volumes:
      - .:/var/www/html
    env_file:
      - src/.env

  mysql:
    image: mysql:8
    restart: always

    volumes:
      - ./seed:/docker-entrypoint-initdb.d
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
      - database-app:/var/lib/mysql
    env_file:
      - mysql/.env
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=$MYSQL_ROOT_PASSWORD",
        ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 60s

volumes:
  database-app:
